export const alphabet = {
  a: {
    title: "A a",
    img: "https://naldzgraphics.net/wp-content/uploads/2014/03/1-alligator-a.jpg",
    animal: "aligator",
    phrase: "An amazing alligator ate an apple",
  },
  b: {
    title: "B b",
    img: "https://naldzgraphics.net/wp-content/uploads/2014/03/2-baboon-b.jpg",
    animal: "baboon",
    phrase: "Barry Baboon bangs bongos",
  },
  c: {
    title: "C c",
    img: "https://naldzgraphics.net/wp-content/uploads/2014/03/3-chameleon-c.jpg",
    animal: "chameleon",
    phrase: "Chameleons carry cherries",
  },
  d: {
    title: "D d",
    img: "https://naldzgraphics.net/wp-content/uploads/2014/03/4-dolphin-d.jpg",
    animal: "dolphin",
    phrase: "Drama dolphin dives deep",
  },
  e: {
    title: "E e",
    img: "https://naldzgraphics.net/wp-content/uploads/2014/03/5-elephant-e.jpg",
    animal: "elephant",
    phrase: "Edward Elephant explains equations",
  },
  f: {
    title: "F f",
    img: "https://naldzgraphics.net/wp-content/uploads/2014/03/6-fox-f.jpg",
    animal: "fox",
    phrase: "Fancy fox forgets fridays",
  },
  g: {
    title: "G g",
    img: "https://naldzgraphics.net/wp-content/uploads/2014/03/7-giraffe-g.jpg",
    animal: "giraffe",
    phrase: "Grandma Giraffe greets green geckoes",
  },
  h: {
    title: "H h",
    img: "https://naldzgraphics.net/wp-content/uploads/2014/03/8-hippopotamus.jpg",
    animal: "hippopotamus",
    phrase: "Happy hippo henry hurries hastily",
  },
  i: {
    title: "I i",
    img: "https://naldzgraphics.net/wp-content/uploads/2014/03/9-ibis-i.jpg",
    animal: "ibis",
    phrase: "Intuitive iguana identified Idris ibis",
  },
  j: {
    title: "J j",
    img: "https://naldzgraphics.net/wp-content/uploads/2014/03/10-jellyfish-j.jpg",
    animal: "jellyfish",
    phrase: "Jiggly jellyfish jump jauntily",
  },
  k: {
    title: "K k",
    img: "https://naldzgraphics.net/wp-content/uploads/2014/03/11-kangaroo.jpg",
    animal: "kangaroo",
    phrase: "Karate kangaroo kick kazillion kickboxers",
  },
  l: {
    title: "L l",
    img: "https://naldzgraphics.net/wp-content/uploads/2014/03/12-lion-l.jpg",
    animal: "lion",
    phrase: "Languishing lions leap lightly",
  },
  m: {
    title: "M m",
    img: "https://naldzgraphics.net/wp-content/uploads/2014/03/13-meerkat-m.jpg",
    animal: "meerkat",
    phrase: "Mamma Meerkat makes mojitos",
  },
  n: {
    title: "N n",
    img: "https://naldzgraphics.net/wp-content/uploads/2014/03/14-narwhal-n.jpg",
    animal: "narwhal",
    phrase: "Narwhal nicknamed needlefish Nate, Noah",
  },
  o: {
    title: "O o",
    img: "https://naldzgraphics.net/wp-content/uploads/2014/03/15-owl-o.jpg",
    animal: "owl",
    phrase: "Olly Owl opens oranges",
  },
  p: {
    title: "P p",
    img: "https://naldzgraphics.net/wp-content/uploads/2014/03/17-penguin-p.jpg",
    animal: "penguin",
    phrase: "Paranoid penguin pursues panic",
  },
  q: {
    title: "Q q",
    img: "https://naldzgraphics.net/wp-content/uploads/2014/03/18-quail.jpg",
    animal: "quail",
    phrase: "Quiet Quail quivers quietly",
  },
  r: {
    title: "R r",
    img: "https://naldzgraphics.net/wp-content/uploads/2014/03/19-rattlesnake-r.jpg",
    animal: "rattlesnake",
    phrase: "Rolling rattlesnakes rapping roughly",
  },
  s: {
    title: "S s",
    img: "https://naldzgraphics.net/wp-content/uploads/2014/03/20-swan-s.jpg",
    animal: "swan",
    phrase: "Silent swans swimming smoothly",
  },
  t: {
    title: "T t",
    img: "https://mir-s3-cdn-cf.behance.net/project_modules/disp/aa898112083085.56287b37df969.jpg",
    animal: "tiger",
    phrase: "Timid tigers touching toes",
  },
  u: {
    title: "U u",
    img: "https://mir-s3-cdn-cf.behance.net/project_modules/disp/8b606b12083085.56276eedbdb69.jpg",
    animal: "unau",
    phrase: "Unusual unau uses umbrella",
  },
  v: {
    title: "V v",
    img: "https://mir-s3-cdn-cf.behance.net/project_modules/disp/1ae24a12083085.56276ecf2d3a6.jpg",
    animal: "vampire bat",
    phrase: "Vampire Bats visiting Vietnam",
  },
  w: {
    title: "W w",
    img: "https://mir-s3-cdn-cf.behance.net/project_modules/disp/a82b1b12083085.56276d1d9dc66.jpg",
    animal: "walrus",
    phrase: "Wally Walrus whispers wishes",
  },
  x: {
    title: "X x",
    img: "https://mir-s3-cdn-cf.behance.net/project_modules/disp/eff58f12083085.56287d6fa0022.jpg",
    animal: "x-ray tetra",
    phrase: "X-ray tetra examines xylophones",
  },
  y: {
    title: "Y y",
    img: "https://mir-s3-cdn-cf.behance.net/project_modules/disp/2bcd9912083085.56287cb4822fe.jpg",
    animal: "yak",
    phrase: "Yellow Yak yoga-ing youthfully",
  },
  z: {
    title: "Z z",
    img: "https://mir-s3-cdn-cf.behance.net/project_modules/disp/95e8f012083085.56287bf26f728.jpg",
    animal: "zebra",
    phrase: "Zany Zebra zippy zigzag",
  },
};

//deep freeze the object
